theme = "starlight"

[editor]
line-number = "relative"
cursorline = true
color-modes = true # Colora la barra di stato in base alla modalit√† (Insert/Normal)

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
